name: "CI"

on: pull_request

jobs:
  check:
    name: Automated checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # TODO: add linting to this repo.
      # - name: Lint files
      #   run: npm run lint

      - name: Run typechecks
        run: npm run typecheck

      # TODO: Once PR #3 is merged, uncomment this.
      # - name: Run tests
      #   run: npm run test:ci

      - name: Run build
        run: npm run build
